-- =====================================================================
-- DataFlip — AWS Glue Data Catalog DDL & Reference Architecture
-- =====================================================================
-- In DataFlip's domain-agnostic architecture, Athena/Glue tables are
-- dynamically discovered and registered by the DataFlip Lambda engine
-- (via PyArrow schema discovery) upon Parquet upload to:
--   s3://${s3_bucket}/<dataset_name>/green/<file>.parquet
--
-- The DDL statements below illustrate:
-- 1. The persistent analytics database.
-- 2. The reference table definition automatically managed by DataFlip.
-- =====================================================================

-- 1. Database Creation (Provisioned via Terraform: aws_glue_catalog_database.dataflip_db)
CREATE DATABASE IF NOT EXISTS dataflip_db;

-- 2. Reference Dynamic Table Template
-- When a dataset is promoted, DataFlip creates or updates the Glue table:
--   Active GREEN:  s3://${s3_bucket}/<dataset_name>/green/
--   Rollback BLUE: s3://${s3_bucket}/<dataset_name>/blue/
-- Columns and types are dynamically discovered from the uploaded Parquet file.

CREATE EXTERNAL TABLE IF NOT EXISTS dataflip_db.<dataset_name> (
    -- Example schema dynamically generated by DataFlip:
    -- id          BIGINT,
    -- timestamp   TIMESTAMP,
    -- metric_name STRING,
    -- value       DOUBLE,
    -- is_active   BOOLEAN
)
STORED AS PARQUET
LOCATION 's3://${s3_bucket}/<dataset_name>/green/'
TBLPROPERTIES (
    'has_encrypted_data'='true',
    'parquet.compression'='SNAPPY'
);

-- =====================================================================
-- ARCHITECTURE NOTE: METADATA-ONLY BLUE/GREEN SWITCHING
-- =====================================================================
-- Root Location Switch:
--   - DataFlip updates the Glue table definition (schema & storage location)
--     in milliseconds via `glue.update_table(TableInput=...)`.
--   - Replaces slow, expensive physical object copying with metadata pointer updates.
--   - Downstream Athena queries instantly resolve the active dataset partition.
-- =====================================================================
